name: BackstopJS Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install Puppeteer browsers
      run: npx puppeteer install

    - name: Give execute permission to backstop binary
      run: chmod +x node_modules/.bin/backstop

    - name: Run BackstopJS reference
      run: npx backstop reference --config=backstop.config.js

    - name: Package reference screenshots
      run: tar -czf reference-screenshots.tar.gz backstop_data/bitmaps_reference

    - name: Upload reference screenshots to GitHub
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"message":"Upload reference screenshots","branch":"gh-pages","content":"'$(base64 reference-screenshots.tar.gz)'"' \
          https://api.github.com/repos/LinkGraph2021/BSJS/contents/backstop_data/bitmaps_reference/$(date +%Y%m%d%H)
