name: BackstopJS Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install Puppeteer browsers
      run: |
        npm install puppeteer

    - name: Give execute permission to backstop binary
      run: chmod +x node_modules/.bin/backstop

    - name: Run BackstopJS reference
      run: npx backstop reference --config=backstop.config.js

    - name: Package reference screenshots
      run: tar -czf reference-screenshots.tar.gz backstop_data/bitmaps_reference

    # Use actions/upload-artifact@v3 to upload the screenshots
    - name: Upload reference screenshots as artifact
      uses: actions/upload-artifact@v3
      with:
        name: reference-screenshots
        path: reference-screenshots.tar.gz
