name: BackstopJS Tests & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Give execute permission to Backstop binary
        run: chmod +x node_modules/.bin/backstop

      - name: Run BackstopJS reference
        run: npx backstop reference --config=backstop.config.js

      - name: Run BackstopJS test (optional)
        run: npx backstop test --config=backstop.config.js

      - name: Upload report as GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: backstop_data/html_report

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
