name: BackstopJS Visual Tests

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Puppeteer Chrome
        run: |
          npm install puppeteer
          npx puppeteer browsers install chrome

      - name: Give execute permission to backstop binary
        run: chmod +x node_modules/.bin/backstop

      - name: Run BackstopJS reference
        run: npx backstop reference --config=backstop.config.js

      - name: Move screenshots to deploy folder
        run: |
          mkdir -p public
          cp -r backstop_data/bitmaps_reference public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
